export {default as Settings} from "./pages/settings/"
export {default as MyOrders} from "./pages/my-orders"
export {default as MyInfos} from "./pages/my-infos"
export {default as ChangePassword} from "./pages/change-password"
export {default as ChangePhoneNumber} from "./pages/change-phone-number"