export const ProductType = {
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    CHANGE_QUANTITY: "CHANGE_QUANTITY",
    UPLOAD_PRODUCT: "UPLOAD_PRODUCT",
    TOGGLE_PRODUCT: "TOGGLE_PRODUCT",
    TOOGLE_FAVOURITE:"TOOGLE_FAVOURITE"
}